const titles* = [
    "cabin in the woods",
    "slice of the internet",
    "home on the World Wide Web",
    "bytes",
    "virtual space",
    "website",
    "page",
    "country corner",
    "internet of things",
    "is the place to be",
    "personal digital destination",
    "home for wayward dogs",
    "home of horrors (NOT scary)",
    "dreamscape",
    "cheeseburger in paradise",
    "web of confusion",
    "online oasis",
    "virtual vogon village",
    "pan-galactic gargle blaster",
    "off-world colonies",
    "digital dystopia",
    "postmodern paradise",
    "AI adventureland",
    "mushroom kingdom",
    "1992",
    "Midwestern Way Station",
    "Spin Membrane",

]

const chyrons* = [
    "Now in technicolor",
    "...oh, this is still here?",
    "fueled by Diet Mtn Dew",
    "allegedly",
    "dog hair now included!",
    "enjoy your stay!",
    "FREE bits AND bytes!",
    "wow, what a great audience",
    "startup mode activated",
    "too lazy to think of a new chyron",
    "brought to you by ChatGPT and GPT-3",
    "-1500,+0 LLOC",
    "dogs encouraged",
    "listen to Einstein, not me",
    "so long and thanks for all the bytes",
    "pre-alpha",
    "AI-generated",
    "now engaged",
    "via your local collapsar",
    "it's a relativistic thing, you wouldn't understand",
    "24th century telepaths welcome"
]
