name: build

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    env:
      NIM_VERSION: 2.0.2
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    runs-on: ubuntu-latest

    steps:
    - name: Setup environment
      run: echo "::set-env name=NIM_VERSION::$NIM_VERSION"

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_KEY" > ~/.ssh/deploy.key
        chmod 600 ~/.ssh/deploy.key
        cat >>~/.ssh/config <<END
        Host bhmsh 
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/deploy.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}

    - uses: actions/checkout@v2

    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ env.NIM_VERSION }}

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ env.NIM_VERSION }}

    - name: Install Nim
      if: steps.cache-choosenim.outputs.cache-hit != 'true' || steps.cache-nimble.outputs.cache-hit != 'true'
      run: |
        export CHOOSENIM_CHOOSE_VERSION="$NIM_VERSION"
        curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        sh init.sh -y

    - name: Install zippy
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nimble -y install zippy

    - name: Build project
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nim buildRls
    
    - name: Stop the server
      run: ssh -t bhmsh 'service bhmsh stop'
    
    - name: Copy binary
      run: scp bin/bhm.sh root@bhmsh:home/bhm/

    - name: Start the server
      run: ssh -t bhmsh 'service bhmsh start'